name: Create Release

on:
  push:
    tags:
      - isc-v*

jobs:
  create-release:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Extract info
      id: info
      run: |
        node ./ci/extractInfo.js
      env:
        GITHUB_REF: ${{ github.ref }}
    - name: Create & upload artifact
      run: |
        python -m pip install mkdocs
        npm install
        npm run ${{ steps.info.outputs.distcommand }}
        npx rimraf ./dist/*.yml ./dist/*.yaml ./dist/*.blockmap
        go get -u github.com/tcnksm/ghr
        ./ci/bin/ghr -n "Sabaki v${{ steps.info.outputs.version }}" -prerelease ${{ steps.info.outputs.tag }} ./dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: ${{ steps.info.outputs.ci }}
